### ISSUE TITLE
Bot Crashes on launch

### ISSUE THREAD

**Issue by NotMattch** [Capps0611/DayZ-Player-Leaderboard-Bot#12]
Trying to set the bot up,  have the settings configured as shown but given the following error:

```
....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\structures\Guild.js:307:68)
    at GuildCreateHandler.handle (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (node:events:527:28)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Capps0611** [comment]
Did you properly install of the node packages by running npm i inside of the directory you extracted the zip too? If not do that.

**Comment by NotMattch** [comment]
Hi Capps,

I've run NPM I from inside the directory again and it completed with 


```
....\Discord Bots\DayZ-Player-Leaderboard-Bot-master>npm i

up to date, audited 12 packages in 11s

found 0 vulnerabilities
```

Trying to run the bot ends up with the output:

```
....\DayZ-Player-Leaderboard-Bot-master>npm start

> dayz_player_leaderboard_bot@1.0.0 start
> nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dayzPlayerLeaderboardBot.js`
....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\structures\Guild.js:307:68)
    at GuildCreateHandler.handle (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (....\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (node:events:527:28)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by NotMattch** [comment]
Just wondering if there was any update with this?  Really hoping to get this bot setup to parse the data

**Comment by Erreur32** [comment]
Still the same issue for me

```
$ node -v
v14.21.3

$ npm outdated
Package     Current  Wanted  Latest  Location                 Depended by
async         3.2.0   3.2.4   3.2.4  node_modules/async       leaderboard_bot
basic-ftp     4.6.2   4.6.6   5.0.2  node_modules/basic-ftp   leaderboard_bot
discord.js   11.6.4  11.6.4  14.7.1  node_modules/discord.js  leaderboard_bot

```
even made a npm to last update still not statup but with error now:

```

> dayz_player_leaderboard_bot@1.0.0 start
> nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dayzPlayerLeaderboardBot.js`
.../DayZ-Player-Leaderboard-Bot/node_modules/@discordjs/util/dist/index.js:34
  return () => defaultValue ??= cb();
                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/.../DayZ-Player-Leaderboard-Bot/node_modules/@discordjs/rest/dist/index.js:276:19)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
[nodemon] app crashed - waiting for file changes before starting...

```


Any help for this issue would be gracefull
