### ISSUE TITLE
*ISSUE* Incorrect login details were provided

### ISSUE THREAD

**Issue by BenteTheWagon** [Capps0611/DayZ-Player-Leaderboard-Bot#4]
I have completed some of the errors there have been while setting up this bot.. but I have reached a point now where I don't know what to do.
Bare with me, I'm really new to anything regarding json
I fixed some stuff by doing `npm install -g nodemon`, but the current error I get is the following.

`(node:15420) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\Wagon Rider\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (C:\Users\Wagon Rider\DayZ-Player-Leaderboard-Bot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:393:10)
    at WebSocket.onClose (C:\Users\Wagon Rider\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\Wagon Rider\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\websocket.js:191:10)    at TLSSocket.socketOnClose (C:\Users\Wagon Rider\DayZ-Player-Leaderboard-Bot-master\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside 
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the 
node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I would assume that the problem was something with the bot token, but I have now changed the bot token and made sure it was right. I can't really seem to find the issue or a fix, any help would be highly appreciated. @Capps0611

**Comment by BenteTheWagon** [comment]
@Capps0611 Any help would be greatly appreciated!

**Comment by Capps0611** [comment]
Apologies, I've been a bit busy.

Now for your issue, double check your FTP log in settings in your settings.json file. from the error it looks like you are having trouble connecting to the FTP server you are using.

**Comment by BenteTheWagon** [comment]
@Capps0611 Sorry for the late response on my part (I've been sick)
I have now checked the ftp login details more than 3 times, and I don't think that's the issue, it still might be, but I'm not quite sure.
Hopefully we can find a solution!

**Comment by BenteTheWagon** [comment]
@Capps0611 iI just got it to work!!!
now I just need to add the workshop mod to the server again.

Thank you so much for your time and help.

I might be back another time if I find another problem, but let's not count on that 👍

**Comment by BenteTheWagon** [comment]
@Capps0611 actually, i have ran into a new problem.
The mod on steam doesn't seem to want to make it's own "Leaderboard" file in my server profile folder.
any ideas why this happens?

and this is the error i get
`FTPError: 550 /ServerRPT/Leaderboard: The system cannot find the file specified.`

**Comment by Capps0611** [comment]
@BenteTheWagon that might be an issue with the mod itself, have you tried contacting the mod dev?

**Comment by Capps0611** [comment]
Closing, please re-open if you are still having any issues with my code.
